language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "pypy"
 - "pypy3"
install: 
 - sudo apt-get install zlib1g zlib1g-dev curl
 - sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/
 - pip install pillow unittest2 ; true
script: tests/alltests.py
